name: Sudoku
description: "Sudoku - Trò chơi giải đố thông minh Việt Nam"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2

  # WebView
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.13.0
  webview_flutter_wkwebview: ^3.13.0

  # Tiện ích
  url_launcher: ^6.3.0 # Gửi email
  geolocator: ^10.1.0 # Lấy tọa độ GPS
  geocoding: ^2.1.1 # Chuyển tọa độ thành tên Quốc gia

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Thư viện tạo Icon tự động
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# CẤU HÌNH TẠO ICON TỰ ĐỘNG
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png" # BẠN CẦN ĐỔI TÊN FILE playstore.png THÀNH icon.png
  min_sdk_android: 21
  # Cấu hình cho Android đời mới (tránh bị viền trắng)
  adaptive_icon_background: "#000000" # Màu nền đen (trùng màu logo của bạn)
  adaptive_icon_foreground: "assets/images/icon.png"