name: Jun_Sudoku
description: "Jun Sudoku - Trò chơi giải đố thông minh Việt Nam"
publish_to: "none"
version: 2.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2

  # WebView
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.13.0
  webview_flutter_wkwebview: ^3.13.0

  # Tiện ích
  url_launcher: ^6.3.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # --- THÊM DÒNG NÀY ---
  audioplayers: ^6.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # --- THÊM DÒNG NÀY (Nhớ tạo đúng thư mục) ---
    - assets/sound-effects/

# CẤU HÌNH TẠO ICON TỰ ĐỘNG (Giữ nguyên)
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/icon.png"
